### Create Organization
POST http://localhost:5217/api/v1/organizations
Content-Type: application/json

{
    "name":"Acme Engineering"
}

### Get Organization
GET http://localhost:5217/api/v1/organizations/515f4ca3-2b37-4b04-b067-324024d1ed41
