### Create Organization
POST http://localhost:5217/api/v1/organizations
Content-Type: application/json

{
    "name":"Acme Engineering"
}

### Get Organization
GET http://localhost:5217/api/v1/organizations/e2fdb5e1-a4b9-4383-adab-321cb8b47827
